### ISSUE TITLE
New method: webpage "as user would see" - like htmlunit page.asNormalizedText()

### ISSUE THREAD

**Issue by BigB84** [headzoo/surf#128]
Hi, 
I write app that needs to read webpage as would user see, then save it to file (without interaction).
Here's a [webpage](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0) I need to process.

I've read the docs and tried to do it with bow.Body() but I get the html source so with tags like `<pre>` `<p>` so bufio reads it and it does mess, of course I can post-process removing all `<` started etc. but It's a lot of code to cover all scenarios.

I've done it in java once with htmlunits [page.asNormalizedText()](https://github.com/HtmlUnit/htmlunit/blob/dbe73274beed22d0bf2d7dae6ba84996b7b25dd9/src/main/java/com/gargoylesoftware/htmlunit/html/DomNode.java#L800) or python with selenium (I know there's selenium for go, but I'd rather omit additional webdriver config etc. that's why I also use your library :))

Do you think it'd be good to add such feature? Or if, you don't think it's a good idea, could you help me find other solution?
Thanks in advance

**Comment by headzoo** [comment]
You could try using a specific css selector instead of bow.Body(). For instance.

```go
bow.Dom().Find("body p pre").Each(func(_ int, s *goquery.Selection) {
    fmt.Println(s.Text())
})
```

That should give you the text inside of the inner <pre> tag.

**Comment by BigB84** [comment]
Thanks! :)
