### ISSUE TITLE
ResolveUrl() don't work with tag <base href="...">

### ISSUE THREAD

**Issue by MashinaMashina** [headzoo/surf#132]
ResolveUrl() don't work with tag `<base href="...">`

If page contains tag `<base href="...">,` resolving must be relatively href attribute, now is relatively browser url.

**Comment by headzoo** [comment]
Looks good. Thanks for the PR.

**Comment by MashinaMashina** [comment]
@headzoo when I can view my fix after
go get github.com/headzoo/surf
or
go get gopkg.in/headzoo/surf.v1
?

I need this fix in my project, but I dont want to edit local package

**Comment by headzoo** [comment]
I pushed tag v1.0.1. Give go get a try now using that version.
