### ISSUE TITLE
Add support for calling Browser.Post from initial state

### ISSUE THREAD

**Issue by Mojofreem** [headzoo/surf#14]
The Post method of Browser references bow.Url(), which implies that the browser instance has already established a connection (via a GET call?) prior to the POST call. This causes a nil pointer dereference if you attempt to make a Post call with a newly instantiated Browser instance. My current workaround is to make a dummy get call to the same url prior to the POST call.

**Comment by headzoo** [comment]
Sounds like a good fix. So far my general philosophy has been to treat Surf like a real browser, and generally with real browsers a POST request follows a GET request, which is knowledge used by web developers to block spiders and bots that POST to forms without first making a GET request for the page containing the form. But Surf wouldn't be useful if we rigidly stick to the "real browser" way of thinking, so I don't see a problem with starting a session with a POST request.

I'll take a look at making the change today.

**Comment by headzoo** [comment]
This has been fixed in the latest master.
