### ISSUE TITLE
Some problems with encoding.

### ISSUE THREAD

**Issue by AlexandrButenko** [headzoo/surf#30]
Hello from Russia!
I'am gonna try to use golang instead ruby (mechanize). But now i have a problem with encoding. When i trying to get some page (ex. http://google.com/) - i got some words on Russian like a diamond with a question. What i should to do?

P.S. I tryed to change response to utf-8 and cp1251...

Problem code;

```go
a := surf.NewBrowser()
a.Open("http://google.com/")
fmt.Println(a.Body()) // For example
```
and here i have bad characters.

**Comment by cornerot** [comment]
Привет, коллега.
Да, действительно, есть такая проблема. Сегодня-завтра постараюсь глянуть в чём дело.

**Comment by cornerot** [comment]
Проблема не в surf, а в кодировке, в которой отдаёт google.
К примеру:

```go
a := surf.NewBrowser()
a.Open("http://mail.ru/")
fmt.Println(a.Body())
```

отработает нормально.

А вот собственно причина:

```
curl www.google.ru | iconv -f cp1251 -t utf8
```

**Comment by cornerot** [comment]
Hello, headzoo.
You can close this issue.

**Comment by AlexandrButenko** [comment]
10/10. Спасибо большое!

**Comment by cornerot** [comment]
Пожалуйста!
