### ISSUE TITLE
Docs down?

### ISSUE THREAD

**Issue by sethgrid** [headzoo/surf#33]
http://www.gosurf.io/ seems to be down.

**Comment by lennyxc** [comment]
I was looking for them too. I'm not sure if this project is still being actively maintained. Here is the pull request I've submitted to change the URL: https://github.com/headzoo/surf/pull/32

**Comment by Entalpi** [comment]
This project looks pretty dead if no one can merge this little fix. :-1:

**Comment by headzoo** [comment]
I'm merging the pull request now. I don't have much time to work on the project, but this was a pretty big stumbling block for people who want to poke around at the code.
