### ISSUE TITLE
No support for form input types checkbox, radio or select multi

### ISSUE THREAD

**Issue by jtwatson** [headzoo/surf#43]
There is a serious issue when handling forms that have checkbox's, radio buttons or select multiple input types.  If you submit a form that has checkbox's, they will all be checked when submitted regardless of there state as downloaded.  Forms with radio buttons will have the last button selected regardless of original state.  Disabled fields are submitted, etc.

I will be submitting a PR shortly to implement robust support for Checkboxes, Radio buttons and Select multiple input elements.  It also handles disabled fields properly.

**Comment by jtwatson** [comment]
When do you think we can get a review of the PR for this issue?

**Comment by lielran** [comment]
the submit don't return any error while one of the inputs are not found. 
also inputs are found only by name.

**Comment by lxt2** [comment]
@jtwatson ok to close this now?

**Comment by jtwatson** [comment]
I think so. @lielran left a comment that I haven't had time to look into yet.
