### ISSUE TITLE
Could you move the docs to godoc?

### ISSUE THREAD

**Issue by abhi18av** [headzoo/surf#51]
Hey @headzoo 

I wanted to add this to the [awesome-go](https://github.com/avelino/awesome-go) list but the requirement is of 

- github.com repo: 
- godoc.org: 
- goreportcard.com: 
- coverage service link (gocover, coveralls etc.): 

Could you help me out with this commit?

**Comment by headzoo** [comment]
Hi, godoc.org documents packages automatically. https://godoc.org/github.com/headzoo/surf Are you asking whether I can write better inline documentation for the godoc tool?

**Comment by abhi18av** [comment]
Ah, right. I'm such a noob sometimes :smile: 

Well, could you just add that badge/link to the docs on the Readme ?

**Comment by headzoo** [comment]
Added. Also thanks for pointing out goreportcart.com. I didn't even know it existed. Pretty cool.

**Comment by abhi18av** [comment]
Thanks :)
