### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by lxt2** [headzoo/surf#65]
So currently there is a tag that points to v1: 

https://github.com/headzoo/surf/commit/3ab5b77981eb350c4821694b70cddc90d59e791c =>
`gopkg.in/headzoo/surf.v1`

and there is work on a v2 branch. 

Thoughts on how we should proceed with point releases in between? 

My suggestion would be to adopt [semver](http://semver.org/), and then keep using gopkg.in:

> When using branches or tags to version the GitHub repository, gopkg.in understands that a selector in the URL such as "v1" may be satisfied by a tag or branch "v1.2" or "v1.2.1" (vMAJOR[.MINOR[.PATCH]]) in the repository, and will select the highest version satisfying the requested selector.

**Comment by headzoo** [comment]
Semver with gopkg.in works for me.

**Comment by lxt2** [comment]
How about master vs dev? People are going to keep forgetting, unless there is a good reason, my vote would be to use master.

**Comment by lxt2** [comment]
I cleaned up the v1 release, it's now v1.0.0, and I fleshed out the release notes:  https://github.com/headzoo/surf/releases/tag/v1.0.0

**Comment by headzoo** [comment]
> my vote would be to use master.

Same here.

**Comment by bscott** [comment]
@headzoo Dep was annouced at GopgerCon, any plans to move to Dep instead for Dep management.

**Comment by headzoo** [comment]
@bscott - I would feel better about recommending Dep once it's been added to the Go toolchain. For now we could add Dep instructions to the documentation, while continuing to reference gopkg.in in the primary docs until Dep is truly official.

**Comment by lxt2** [comment]
Yeah, dep still is undercooked from my use of it.
