### ISSUE TITLE
Not compitable with https

### ISSUE THREAD

**Issue by killernova** [headzoo/surf#88]
When requests url with https, an error occurs: x509: certificate has expired or is not yet valid

**Comment by Joffcom** [comment]
I have been using it with https, are you using a self signed certificate?

**Comment by killernova** [comment]
@Joffcom Yes, this problem will only occur when visit a self-signed certificate website, is there any solutions?

**Comment by Joffcom** [comment]
Have a look at the browser.SetTransport method it allows you to set options for the http client so may do what you are after.

I won’t be able to check for a few hours but that is where I would start.

**Comment by killernova** [comment]
This solves my problem, thanks so much! The issue could be closed now.
